"""riesgo en pujas

Revision ID: 2a7d75cd5f85
Revises: e8506013e3e2
Create Date: 2026-09-29 15:37:24.988390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7d75cd5f85'
down_revision: Union[str, Sequence[str], None] = 'e8506013e3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pujas', sa.Column('riesgo', sa.Integer(), server_default='0', nullable=False))
    op.add_column('pujas', sa.Column('motivos_riesgo', sa.Text(), nullable=True))
    op.add_column('pujas', sa.Column('extendio_cierre', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pujas', 'extendio_cierre')
    op.drop_column('pujas', 'motivos_riesgo')
    op.drop_column('pujas', 'riesgo')
    # ### end Alembic commands ###
