"""crear tablas iniciales

Revision ID: e8506013e3e2
Revises: 
Create Date: 2026-09-29 06:25:02.411370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8506013e3e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('productor', 'comprador', name='rol_usuario'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_cosecha', sa.Date(), nullable=False),
    sa.Column('vida_util_dias', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['productor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_productor_id'), 'productos', ['productor_id'], unique=False)
    op.create_table('subastas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incremento_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('programada', 'activa', 'finalizada', 'cancelada', name='estado_subasta'), nullable=False),
    sa.Column('extensiones', sa.Integer(), nullable=False),
    sa.Column('ganador_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ganador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subastas_producto_id'), 'subastas', ['producto_id'], unique=False)
    op.create_table('pujas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subasta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subasta_id'], ['subastas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pujas_subasta_monto', 'pujas', ['subasta_id', 'monto'], unique=False)
    op.create_index(op.f('ix_pujas_usuario_id'), 'pujas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pujas_usuario_id'), table_name='pujas')
    op.drop_index('ix_pujas_subasta_monto', table_name='pujas')
    op.drop_table('pujas')
    op.drop_index(op.f('ix_subastas_producto_id'), table_name='subastas')
    op.drop_table('subastas')
    op.drop_index(op.f('ix_productos_productor_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
